### ISSUE TITLE
Feature request: activate the plugin without turning on default mappings

### ISSUE THREAD

**Issue by andmis** [lervag/lists.vim#2]
It would be great if there were a way to activate the plugin (`:ListsEnable`) without its default mappings. I have my own mappings for `lists.vim` commands, and I need to disable yours because I use `<Leader>w…` for something else.

Thanks for the plugin! It is very nice. I appreciate that it is polished, consistent, and generally high-quality and well-thought-out. I especially appreciate that it doesn't activate itself automatically, because indeed I don't need `lists.vim` in every buffer. Although, there is probably no harm in the `<Plug>(lists-…)` commands always being defined, and if the `<Plug>` commands were always defined it would actually resolve my issue because I would just define my custom mappings in my own `activate_lists_mode` function without calling `:ListsEnable`. (I need my own `activate_lists_mode` regardless because I want to customize the mappings.)

**Comment by lervag** [comment]
Thanks! I believe `g:lists_enable_default_maps` should resolve this?

**Comment by lervag** [comment]
One possibility could be to add a `ListsEventEnabled` user event. Then you could hook into it and add your mappings when lists.vim is loaded?

**Comment by andmis** [comment]
Thanks! `g:lists_enable_default_maps` resolves this for me.

Regarding adding a user event, I think that's overkill. At least I wouldn't use it. I think it is great that `ListsEnable` exists to turn on your plugin, and I don't see a clear use case for an event since a user can just put whatever code they want to run after `ListsEnable` right after wherever their `ListsEnable` call lives. (I suppose unless they are running `:ListsEnable` interactively, but then they can write their own command that does `:ListsEnable` and whatever else they want to have happen.) IMHO it's better for `ListsEnable` to mean exactly "turn on `lists.vim`".

**Comment by lervag** [comment]
Great! Your reasoning is good. Notice, though, some people (me included) enable lists.vim by filetype with `g:lists_filetypes`. The hook could potentially be relevant in that context. However, configuring with a custom event is not really much better than configuring the filetype autocommands and using `:ListsEnable` manually, so I agree that there is not much to gain here.
