### ISSUE TITLE
:ListsToggle fails for item on the first line

### ISSUE THREAD

**Issue by protist** [lervag/lists.vim#8]
# Description

1. Use a blank `.vimrc`
2. Create a new file
3. On the first list, type `* [ ] foo`
4. Enable lists.vim with `:ListsEnable`
5. Attempt to toggle item with `:ListsToggle`.

Expected behaviour: line should toggle to `* [x] foo`

Observed behaviour: line does not toggle.

If I add a new line above this item, toggling will work.

# Minimal working example

Empty `.vimrc` and the following test files.

Toggle fails:
```vim
* [ ] foo
```

Toggle works:
```vim
                "<--- this is actually a blank line
* [ ] foo
```

This was previously reported in #1, but I'll open a new issue here.

I don't get any errors. I'm using the latest vim 9.1.0707, in an up-to-date Arch Linux system.

**Comment by lervag** [comment]
Strange. I can't reproduce this with neovim. Testing with Vim now.

**Comment by lervag** [comment]
Ok, seems to work with Vim as well for me. I have a minimal vimrc file like this:

```vim
" mwe.vim
set nocompatible
set runtimepath^=~/.local/plugged/lists.vim
set noswapfile
set noshowmode
set nomore

runtime plugin/lists.vim
```

Then I do `vim --clean -u mwe.vim` and I follow your recipe. I also use Vim 9.1.707 on Arch Linux.

Could you repeat the test with the minimal vimrc file? I.e., copy the contents above into a file `mwe.vim`, update the `runtimepath` to point to the plugin location (you probably do not use `.local/plugged`).

**Comment by protist** [comment]
Thanks @lervag. Very weird. I did as you suggest, and it still fails for me as per the original report. I'm not entirely sure what I'm doing so here are a few clarifications.

I originally didn't read your comment properly, and used your `mwe.vim` verbatim, i.e. without changing `runtimepath`. This still worked (i.e. failed on the first line, toggled on the second). I then tried changing `runtimepath` to `/usr/share/vim/vimfiles/plugin/lists.vim`, and no difference. In fact, commenting this out entirely also works!

Actually, it seems like `--clean` is not enough to exclude all other plugins. e.g. `:scriptnames` shows a bunch of plugins being loaded, e.g.

```
 90: /usr/share/vim/vimfiles/autoload/ale.vim
 91: /usr/share/vim/vimfiles/autoload/recover.vim
 92: /usr/share/vim/vimfiles/autoload/gitgutter.vim
```

I had a brief search, but I'm not sure how to start vim without loading any of my system-installed plugins. (These are all installed from the AUR.)

**Comment by lervag** [comment]
Oh, please: DON'T install plugins with AUR! (!!!!!!!!)

Instead, do this:

* First: Remove _all_ plugins you've installed through `pacman` or AUR. Take note of them so that you can install them again within your vimrc file in a proper way.
* Learn to install your plugins through a plugin manager. Today `lazy.nvim` is the most popular, but it only works with Neovim. On Vim, I would suggest vim-plug - it is simple and good.
* Now install your plugins again using the plugin manager.

I believe this should also help resolve your issue.

**Comment by protist** [comment]
Thanks @lervag . What is the rationale with this? I much prefer AUR because (a) it will update with my other system updates. Otherwise, it's just another platform to remember (and forget) to update. (b) then all users will have access to plugins, meaning only a single install.

AUR generally works well for me, but I understand if you won't support this method of installation.

**Comment by lervag** [comment]
> Thanks @lervag. What is the rationale with this? I much prefer AUR because (a) it will update with my other system updates. Otherwise, it's just another platform to remember (and forget) to update.

I can understand this. However, with a package manager, it is very easy to update your plugins. Also, you have _full_ control. You will _not_ find all good plugins in AUR. And it becomes a mess if you install some plugins via AUR and others by other means.

In my opinion, keeping you Vim config and all related plugins in one place is a much easier way to handle things. Yes, you _do_ have to remember to update. But most plugin managers have some concept of auto-update. I don't like that, as I instead update manually once a week.

> (b) then all users will have access to plugins, meaning only a single install.

They don't have _access_ to plugins - they are forced to use them. The AUR places the plugins in the shared runtime folders, which means it becomes a hazzle to disable them.

> What is the rationale with this?

In my (humble) opinion, you should keep your configuration clear, explicit and easily debuggable. This requires a few properties:

* It should be very easy to change your configuration, both options and plugin config.
* It should be easy to see which plugins you are actually using.
* It should be easy to disable plugins.
* It should be easy to install new plugins.
* It should be easy to debug, e.g. by running with a very clean config such as the one I showed you earler.
* It should be easy to migrate your Vim config to other computers, including ones that doesn't use Arch Linux. In fact, it should be easy to get up and running with your Vim config on a new system within a minute or two.

Installing plugins via system package manager, e.g. AUR, breaks four of the above properties (the first one is probably possible to keep intact).

> AUR generally works well for me, but I understand if you won't support this method of installation.

It's good for you if it works well. But I won't support this and I never will. Sorry.

**Comment by protist** [comment]
Thanks for the detailed reply @lervag . Very much appreciated. I understand your points, but I think in my case I'll probably stay with AUR. The major point I agree with is that my config should be clearer... but unfortunately after years of adding and subtracting from my `.vimrc` it's a bit of a mess anyway! Honestly, the biggest barrier to migrating is that I don't really have the time (or bandwidth) to change all my systems at the moment! I'll put it in the "todo one day" pile.

And totally understand that you can't support AUR. I'll close this now as unsupported, but having said that, it's probably not even a problem coming from this project anyway! Thanks again.

**Comment by lervag** [comment]
I'm glad to hear my reply was helpful :)
